### ISSUE TITLE
Possible TODO items to move forward IKVM

### ISSUE THREAD

**Issue by lextm** [windwardadmin/ikvm#1]
@DavidThi808 Thanks for showing your passion to move the project forward.

You said that you have contacted IKVM developers mailing list a month ago, so I assume that you didn't get the responses you wanted.

I have taken over several projects in the past few years (like DockPanel Suite, Obfuscar, and PHP Manager for IIS) sand I understand it is not any easy task. I am writing my ideas below and hope they help,

1. This repo does not contain all the commits of IKVM CVS repo. This does not make full use of the history, and can have some issues in the future (when you need to reference to an old commit and the original changes). You might need to do CVS to Git conversion once again, and then cherry pick the changes in this repo, and force push to replace this repo.
1. This repo is hosted under a company account. I am not saying it's bad, but other contributors might not like this option. It is more common to create a dedicate organization (like `IKVMGroup`) around an open source project.
1. There is no public roadmap anywhere to state your vision of this fork and your detailed plan (like which bugs are under tracking, and which features are under consideration). That prevents others (like me) to promote your initiative to broader developer communities who might be interested in this (and who might later contribute as well).
1. It is probably hard to get the domain name ikvm.net (did you contact Jeroen Frijters?) so you might need to create a new homepage to interact with whoever is interested in this project.

IKVM is a larger project, and wish you all the best to revive it.

**Comment by ghost** [comment]
Hi;

Those are all good points. However, we’re not trying to doing anything more than fix any serious issues that we hit and offering a repository for anyone else who hits the same. So unlikely we’ll do those other steps. If someone else wants to run with it, then we’ll happily turn this all over to them. To date we’ve made one change.

Thanks – dave


[cid:image003.png@01D3EC5F.44EB35B0]

Dave Thielen
CEO, Windward Studios
windwardstudios.com<https://www.windwardstudios.com/?utm_medium=email&utm_source=signatureline&utm_campaign=link-p&utm_content=link>
david@windwardstudios.com<mailto:david@windwardstudios.com>  |  LinkedIn<https://www.linkedin.com/in/davethielen/>
Schedule an Appointment<https://calendly.com/davidthielen>
P. 1-303-499-2544 x 1185  C.1-720-352-0676


“Thank goodness for Windward. We had been wasting hundreds of hours hand coding report templates…Windward automates the process and helps us get our customers the data they need.”
— Tom N., President and CEO of ArtsVision



More Customer Reviews…<https://www.windwardstudios.com/customer-reviews?utm_medium=email&utm_source=signatureline&utm_campaign=link-p&utm_content=link>
